Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "nginxserver" do |webserver|
    webserver.vm.provider :virtualbox do |v|
      v.name = "nginxserver"
      v.memory = "1024"
      v.cpus = "1"
    end
    webserver.vm.hostname = "nginxserver"
    webserver.vm.network "forwarded_port", guest: 80, host: 8080
    webserver.vm.provision "ansible" do |nginx|
        nginx.playbook = "configure_nginx.yml"
    end
    webserver.vm.provision "ansible" do |ssh|
        nginx.playbook = "configure_ssh.yml"
    end
  end
end