services:
  proxy:
    image: nginx:1.25.1-alpine
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: app
      target: builder
    ports:
      - 8000:80    
