---
AWSTemplateFormatVersion: "2010-09-09"

Description: EC2

Resources:

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId:
        Fn::ImportValue:
          PublicAId
      ImageId: 'ami-077f3abe5acce17a0'
      InstanceType: 't3.micro'
      KeyName:
        Fn::ImportValue:
          RSAKeyName
      SecurityGroupIds:
        - Fn::ImportValue:
            WebServerSGId
      Tags:
        - Key: Name
          Value: 'cf-web-server'
