---
AWSTemplateFormatVersion: "2010-09-09"

Description: RSA

Resources:

  RSAKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: 'cf-rsa-key-pair'
      PublicKeyMaterial: '<your custom id_rsa.pub>'

Outputs:

  RSAKeyName:
    Description: RSA Key Name
    Value: !Ref RSAKey
    Export:
      Name: RSAKeyName

