global:
  scrape_interval:     15s
rule_files:
  - "/tmp/alerts/alert.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.49.2:30067']

